name: Release Preview Nuget Package

on:
  push:
    branches: [ dev ]

jobs:
  build-artifact:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v2
   - name: Setup .NET
     uses: actions/setup-dotnet@v1
     with:
       dotnet-version: 5.0.x
   - name: Restore dependencies
     run: dotnet restore
   - name: Build TwitchLib.Api
     run: dotnet build -c Release --no-restore
   - name: Pack TwitchLib.Api
     run: dotnet pack TwitchLib.Api.sln -v normal -c Release -o nugets --no-build --version-suffix "preview-${{ github.sha }}"
   - name: Upload Build Artifact
     uses: actions/upload-artifact@v2
     with:
       name: nugets
       path: ./nugets/*.nupkg
     
  prerelease:
    needs: build-artifact
    runs-on: ubuntu-latest

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v1
      with:
       name: nugets
    - name: Push to Nuget
      run: dotnet nuget push "./nugets/*.nupkg" -k ${{ secrets.API_NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
